---
- name: install docker on all managed nodes
  hosts: all
  tasks:
   - name: install python
     apt:
      name: "{{item}}"
      state: present
      update_cache: yes
     with_items:
      - python2.7
      - python-pip 
   - name: install docker
     shell: "{{item}}"
     with_items:
      - curl -fsSL https://get.docker.com -o get-docker.sh
      - sh get-docker.sh
      - pip install docker-py
