---
- name: install and uninstall tomcat on managed nodes
  hosts: all
  tasks:
   - name: install tomcat8
     docker_container:
      image: tomcat
      name: webserver
   - name: stop the webserver
     docker_container:
      name: webserver
      state: stopped
   - name: delete the webserver
     docker_container:
      name: webserver
      state: absent
     

