---
- name: docker compose installation
  hosts: 172.31.41.183
  tasks:
   - name: installing
     shell: "{{item}}"
     with_items:
      - sudo curl -L "https://github.com/docker/compose/releases/download/1.25.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
      - sudo chmod +x /usr/local/bin/docker-compose
     
